name: proj
channels:
  - huggingface
  - pytorch
  - nvidia
  - defaults
  # - conda-forge
dependencies:
# - nvidia::cudatoolkit
- torchvision
- pytorch::pytorch
- numpy
- transformers
- datasets
- evaluate
- matplotlib
- tqdm
- scikit-learn
- conda-forge::openai
- ipykernel
