python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name EleutherAI/gpt-j-6B --ll_save_loc results/EleutherAI_gpt-j-6B-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name EleutherAI/gpt-neo-2.7B --ll_save_loc results/EleutherAI_gpt-neo-2.7B-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name facebook/opt-2.7b --ll_save_loc results/facebook_opt-2.7b-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name gpt2 --ll_save_loc results/gpt2-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name gpt2-large --ll_save_loc results/gpt2-large-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name gpt2-medium --ll_save_loc results/gpt2-medium-scorer/human/squad --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/squad --scoring_model_name gpt2-xl --ll_save_loc results/gpt2-xl-scorer/human/squad --mode score --num_perturbations 50

python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name EleutherAI/gpt-j-6B --ll_save_loc results/EleutherAI_gpt-j-6B-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name EleutherAI/gpt-neo-2.7B --ll_save_loc results/EleutherAI_gpt-neo-2.7B-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name facebook/opt-2.7b --ll_save_loc results/facebook_opt-2.7b-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name gpt2 --ll_save_loc results/gpt2-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name gpt2-large --ll_save_loc results/gpt2-large-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name gpt2-medium --ll_save_loc results/gpt2-medium-scorer/human/xsum --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/xsum --scoring_model_name gpt2-xl --ll_save_loc results/gpt2-xl-scorer/human/xsum --mode score --num_perturbations 50

python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name EleutherAI/gpt-j-6B --ll_save_loc results/EleutherAI_gpt-j-6B-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name EleutherAI/gpt-neo-2.7B --ll_save_loc results/EleutherAI_gpt-neo-2.7B-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name facebook/opt-2.7b --ll_save_loc results/facebook_opt-2.7b-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name gpt2 --ll_save_loc results/gpt2-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name gpt2-large --ll_save_loc results/gpt2-large-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name gpt2-medium --ll_save_loc results/gpt2-medium-scorer/human/writing --mode score --num_perturbations 50
python perturb.py --mask_filling_model t5-large --folder_to_perturb UNUSED --folder_of_perturbs perturbations/human/writing --scoring_model_name gpt2-xl --ll_save_loc results/gpt2-xl-scorer/human/writing --mode score --num_perturbations 50
